# Generated by Django 4.0.3 on 2022-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=10, unique=True)),
                ('alias', models.CharField(default='', max_length=20)),
                ('last_access', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
